# Sentinel-1 flood mapping of the 2024 Kenya long-rains floods

Regenerates every number and figure in the paper from public data. Each stage writes to `data/`, `outputs/` or `paper/` and caches large intermediates in `data/cache/` (gitignored), so a second run skips the downloads. Flood masks and the day-gap table are reused when present; delete `outputs/masks/` and `outputs/day_gap_sensitivity.csv` to recompute them. The U-Net stage runs on a Kaggle GPU (see `kaggle/`); this notebook uses the weights it produces in `models/`, or trains locally if `TRAIN_LOCALLY` is set.

In [1]:
import sys
from pathlib import Path

ROOT = Path.cwd().parent if Path.cwd().name == 'notebook' else Path.cwd()
sys.path.insert(0, str(ROOT / 'pipeline'))

import pandas as pd
pd.set_option('display.width', 160)
TRAIN_LOCALLY = False

## 1. UNOSAT reference

Catalogue every FL20240426KEN product on HDX, download the cumulative shapefile package, and rasterise flood water to the 10 m UTM 37S grid.

In [2]:
import fetch_reference, reference, tana_corridor

fetch_reference.main()
if not reference.TANA_TILES.exists():
    tana_corridor.main()
reference.main()

                                                                                     hdx_name      sensor reference_date  reported_flooded_km2  reported_structures  shp_bytes
3        cumulative-satellite-detected-waters-and-impact-in-kenya-between-24-to-28-april-2024  NOAA-VIIRS     2024-04-24                3800.0                  NaN   20741579
10                              flood-impact-analysis-in-kiambu-county-kenya-as-of-1-may-2024    Pléiades     2024-05-01                  13.0               1815.0   60544290
4                   flood-impact-analysis-in-nairobi-and-kiambu-county-kenya-as-of-1-may-2024    Pléiades     2024-05-01                  17.0               3663.0   59835613
5                 flood-impact-analysis-in-nairobi-and-machakos-county-kenya-as-of-1-may-2024    Pléiades     2024-05-01                  22.0               4246.0   59835613
1                                     flood-impact-analysis-in-nairobi-kenya-as-of-1-may-2024    Pléiades     2024-05-01                   2.0               3387.0   59835613
7                            flood-impact-to-cropland-in-kiambu-county-kenya-as-of-1-may-2024    Pléiades     2024-05-01                   2.0                  NaN   60544290
9                flood-impact-to-cropland-in-nairobi-and-kiambu-county-kenya-as-of-1-may-2024    Pléiades     2024-05-01                   3.0                  NaN   59835613
2              flood-impact-to-cropland-in-nairobi-and-machakos-county-kenya-as-of-1-may-2024    Pléiades     2024-05-01                   4.0                  NaN   59835613
8              landslide-mudslide-impact-in-mai-mahiu-and-kijabe-towns-kenya-as-of-1-may-2024    Pléiades     2024-05-01                   NaN               1338.0   59835613
11  satellite-detected-water-extent-in-garissa-city-and-mororo-village-kenya-as-of-5-may-2024    Pléiades     2024-05-05                  22.0               3377.0   59835613
0                                                          unosat-live-web-map-flood-in-kenya         NaN            NaN                   NaN                  NaN   59835613
6                   water-extent-in-garissa-city-and-mororo-village-kenya-as-of-29-april-2024  Sentinel-2     2024-04-29                  26.0               3440.0   59835613
cumulative archive: https://unosat.org/static/unosat_filesystem/3840/FL20240426KEN_SHP.zip

          aoi    group     sensor reference_date  domain_km2  flood_km2  excluded_cloud_km2
   garissa_s2 riverine Sentinel-2     2024-04-29      161.57      27.94                0.54
   garissa_pl riverine   Pléiades     2024-05-05      107.22      21.74               -0.02
   nairobi_pl    urban   Pléiades     2024-05-01      506.44      59.69               73.25
tana_420_9600 riverine Sentinel-2     2024-04-29       99.86       0.00               -0.00
tana_440_9660 riverine Sentinel-2     2024-04-29      195.95       3.54                0.29
tana_460_9640 riverine Sentinel-2     2024-04-29       46.74       0.00                0.01
tana_460_9660 riverine Sentinel-2     2024-04-29      187.51       5.87               -0.01
tana_480_9640 riverine Sentinel-2     2024-04-29       47.30       0.00                0.01
tana_480_9660 riverine Sentinel-2     2024-04-29      176.79       4.89               -0.01
tana_500_9660 riverine Sentinel-2     2024-04-29      114.10       2.59               -0.00
tana_500_9900 riverine Sentinel-2     2024-04-29       37.85       0.00                0.00
tana_500_9920 riverine Sentinel-2     2024-04-29       20.31       0.00               -0.01
tana_500_9980 riverine Sentinel-2     2024-04-29       97.14       0.00              151.54
tana_520_9580 riverine Sentinel-2     2024-04-29       40.23       0.00                0.00
tana_520_9600 riverine Sentinel-2     2024-04-29       44.28       0.00               -0.00
tana_520_9640 riverine Sentinel-2     2024-04-29       42.74       0.70                0.00
tana_520_9660 riverine Sentinel-2     2024-04-29      105.53       1.18               -0.00
tana_520_9960 riverine Sentinel-2     2024-04-29        0.01       0.00               44.69
tana_520_9980 riverine Sentinel-2     2024-04-29        0.10       0.00              201.63
tana_540_9600 riverine Sentinel-2     2024-04-29      102.87       0.00               -0.00
tana_540_9620 riverine Sentinel-2     2024-04-29       66.14       0.00               -0.00
tana_540_9640 riverine Sentinel-2     2024-04-29       36.79       1.47               -0.00
tana_540_9660 riverine Sentinel-2     2024-04-29       96.61       0.00               -0.00
tana_540_9960 riverine Sentinel-2     2024-04-29        8.33       0.00              222.78
tana_540_9980 riverine Sentinel-2     2024-04-29        0.00       0.00               65.05
tana_560_9600 riverine Sentinel-2     2024-04-29       43.19       0.00                0.85
tana_560_9620 riverine Sentinel-2     2024-04-29       27.47       0.00               -0.00
tana_560_9640 riverine Sentinel-2     2024-04-29       86.44       6.53                0.00
tana_560_9660 riverine Sentinel-2     2024-04-29       73.45       0.02               -0.01
tana_560_9820 riverine Sentinel-2     2024-04-29       84.46       0.00                0.04
tana_560_9900 riverine Sentinel-2     2024-04-29       61.66       0.00               22.84
tana_560_9920 riverine Sentinel-2     2024-04-29       99.75      15.01                0.14
tana_560_9940 riverine Sentinel-2     2024-04-29      117.78      14.56                6.81
tana_560_9960 riverine Sentinel-2     2024-04-29       41.33       1.07               66.43
tana_580_9580 riverine Sentinel-2     2024-04-29      127.81       0.95                0.29
tana_580_9600 riverine Sentinel-2     2024-04-29      175.55       1.00                0.12
tana_580_9620 riverine Sentinel-2     2024-04-29       29.01       0.00                0.00
tana_580_9640 riverine Sentinel-2     2024-04-29      158.08       8.81                0.64
tana_580_9860 riverine Sentinel-2     2024-04-29      132.11       0.05               -0.00
tana_580_9880 riverine Sentinel-2     2024-04-29      235.31       3.09                0.63
tana_580_9900 riverine Sentinel-2     2024-04-29       89.09       1.30              149.93
tana_580_9920 riverine Sentinel-2     2024-04-29       92.45       7.16              135.45
tana_600_9600 riverine Sentinel-2     2024-04-29       38.92       0.04                0.06
tana_600_9620 riverine Sentinel-2     2024-04-29      176.61       2.01                4.15
tana_600_9640 riverine Sentinel-2     2024-04-29      186.53       9.49               95.95
tana_600_9800 riverine Sentinel-2     2024-04-29       34.98       0.06               -0.00
tana_600_9820 riverine Sentinel-2     2024-04-29      162.01      15.60               -0.00
tana_600_9840 riverine Sentinel-2     2024-04-29      235.26       9.62                0.02
tana_600_9860 riverine Sentinel-2     2024-04-29      245.21       6.22                0.00
tana_600_9880 riverine Sentinel-2     2024-04-29      106.37       1.58                1.27
tana_620_9620 riverine Sentinel-2     2024-04-29       24.86       0.01               -0.00
tana_620_9640 riverine Sentinel-2     2024-04-29       42.79       0.02               80.08
tana_620_9660 riverine Sentinel-2     2024-04-29      161.34       7.40               29.89
tana_620_9680 riverine Sentinel-2     2024-04-29      159.49      17.90                2.40
tana_620_9700 riverine Sentinel-2     2024-04-29      203.56       6.48                0.15
tana_620_9740 riverine Sentinel-2     2024-04-29      218.25      17.27               -0.00
tana_620_9760 riverine Sentinel-2     2024-04-29       28.01       0.96                0.00
tana_620_9780 riverine Sentinel-2     2024-04-29      222.17       5.87               -0.00
tana_620_9800 riverine Sentinel-2     2024-04-29      194.63      22.64                0.00
tana_620_9820 riverine Sentinel-2     2024-04-29       91.03      10.75                0.00
tana_640_9700 riverine Sentinel-2     2024-04-29      129.30       6.74                0.00
tana_640_9720 riverine Sentinel-2     2024-04-29      285.68     108.04               -0.00
tana_640_9740 riverine Sentinel-2     2024-04-29       97.25       1.98               -0.00
tana_660_9720 riverine Sentinel-2     2024-04-29      232.08      22.82                0.49
tana_660_9820 riverine Sentinel-2     2024-04-29       82.32       0.00                6.76
tana_680_9720 riverine Sentinel-2     2024-04-29      216.01       3.62               11.85
tana_680_9740 riverine Sentinel-2     2024-04-29      163.08       1.65               11.65
tana_680_9780 riverine Sentinel-2     2024-04-29       65.93       0.02               30.56
tana_680_9820 riverine Sentinel-2     2024-04-29       22.07       0.00                4.95
tana_680_9840 riverine Sentinel-2     2024-04-29       48.78       0.00               87.41
tana_700_9740 riverine Sentinel-2     2024-04-29       37.39       0.53               38.08
tana_700_9760 riverine Sentinel-2     2024-04-29       66.86       0.35               22.65
tana_700_9780 riverine Sentinel-2     2024-04-29       37.36       1.54               28.65

## 2. Sentinel-1 passes

Post-event pass nearest each reference date and a same-orbit dry-season pass.

In [3]:
import pick_scenes

pick_scenes.main()
pd.read_csv(pick_scenes.SCENES).query("~aoi.str.startswith('tana_')")

          aoi reference_date  post_date  day_gap  headline   pre_date  post_cover  pre_cover  relative_orbit orbit_state  n_passes_within_gap
   garissa_s2     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
   garissa_pl     2024-05-05 2024-05-08        3      True 2024-02-26       1.000      1.000             159   ascending                    1
   nairobi_pl     2024-05-01 2024-05-01        0      True 2024-02-19       1.000      1.000              57   ascending                    2
tana_420_9600     2024-04-29 2024-05-01        2      True 2024-02-19       1.000      1.000              57   ascending                    1
tana_440_9660     2024-04-29 2024-05-01        2      True 2024-02-19       1.000      1.000              57   ascending                    1
tana_460_9640     2024-04-29 2024-05-01        2      True 2024-02-19       1.000      1.000              57   ascending                    1
tana_460_9660     2024-04-29 2024-05-01        2      True 2024-02-19       1.000      1.000              57   ascending                    1
tana_480_9640     2024-04-29 2024-05-01        2      True 2024-02-19       1.000      1.000              57   ascending                    1
tana_480_9660     2024-04-29 2024-05-01        2      True 2024-02-19       1.000      1.000              57   ascending                    1
tana_500_9660     2024-04-29 2024-05-01        2      True 2024-02-19       1.000      1.000              57   ascending                    1
tana_500_9900     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_500_9920     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_500_9980     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_520_9580     2024-04-29 2024-05-01        2      True 2024-02-19       0.999      0.999              57   ascending                    2
tana_520_9600     2024-04-29 2024-05-01        2      True 2024-02-19       1.000      1.000              57   ascending                    2
tana_520_9640     2024-04-29 2024-05-01        2      True 2024-02-19       1.000      1.000              57   ascending                    2
tana_520_9660     2024-04-29 2024-05-01        2      True 2024-02-19       1.000      1.000              57   ascending                    2
tana_520_9960     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_520_9980     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_540_9600     2024-04-29 2024-05-01        2      True 2024-02-19       1.000      1.000              57   ascending                    2
tana_540_9620     2024-04-29 2024-05-01        2      True 2024-02-19       1.000      1.000              57   ascending                    2
tana_540_9640     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_540_9660     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_540_9960     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_540_9980     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_560_9600     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_560_9620     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_560_9640     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_560_9660     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_560_9820     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_560_9900     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_560_9920     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_560_9940     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_560_9960     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_580_9580     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_580_9600     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_580_9620     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_580_9640     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_580_9860     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_580_9880     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_580_9900     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_580_9920     2024-04-29 2024-04-26       -3      True 2024-02-26       0.999      0.999             159   ascending                    1
tana_600_9600     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_600_9620     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_600_9640     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_600_9800     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_600_9820     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_600_9840     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_600_9860     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_600_9880     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_620_9620     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_620_9640     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_620_9660     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_620_9680     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_620_9700     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_620_9740     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_620_9760     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_620_9780     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_620_9800     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_620_9820     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_640_9700     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_640_9720     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_640_9740     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_660_9720     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_660_9820     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_680_9720     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_680_9740     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_680_9780     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_680_9820     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_680_9840     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_700_9740     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1
tana_700_9760     2024-04-29 2024-04-26       -3      True 2024-02-26       0.999      0.999             159   ascending                    1
tana_700_9780     2024-04-29 2024-04-26       -3      True 2024-02-26       1.000      1.000             159   ascending                    1

,aoi,reference_date,post_id,post_date,day_gap,headline,pre_id,pre_date,post_cover,pre_cover,relative_orbit,orbit_state,n_passes_within_gap
0,garissa_s2,2024-04-29,S1A_IW_GRDH_1SDV_20240426T154032_20240426T1540...,2024-04-26,-3,True,S1A_IW_GRDH_1SDV_20240226T154031_20240226T1540...,2024-02-26,1.0,1.0,159,ascending,1
1,garissa_pl,2024-05-05,S1A_IW_GRDH_1SDV_20240508T154032_20240508T1540...,2024-05-08,3,True,S1A_IW_GRDH_1SDV_20240226T154031_20240226T1540...,2024-02-26,1.0,1.0,159,ascending,1
2,nairobi_pl,2024-05-01,S1A_IW_GRDH_1SDV_20240501T154818_20240501T1548...,2024-05-01,0,True,S1A_IW_GRDH_1SDV_20240219T154816_20240219T1548...,2024-02-19,1.0,1.0,57,ascending,2

## 3. GRD processing against Earth Engine

Processes the original scenes onto Sen1Floods11 chip grids and compares them with the Earth Engine chips.

In [4]:
import fetch_sen1floods11, validate_grd

fetch_sen1floods11.main()
validate_grd.main()

 ID  location chip_prefix ISO_CC    s1_date    s2_date      orbit  rel_orbit_num  VH_thresh  hand_chips  africa  east_africa
  1   Bolivia     Bolivia    BOL 2018/02/15 2018/02/15 DESCENDING          156.0     -20.44          15   False        False
  2     Ghana       Ghana    GHA 2018/09/18 2018/09/19  ASCENDING          147.0     -22.81          53    True        False
  3     India       India    IND 2016/08/12 2016/08/12 DESCENDING           77.0     -21.56          68   False        False
  4  Cambodia      Mekong    KHM 2018/08/05 2018/08/04  ASCENDING           26.0     -23.06          30   False        False
  5   Nigeria     Nigeria    NGA 2018/09/21 2018/09/20  ASCENDING          103.0     -21.94          18    True        False
  6  Pakistan    Pakistan    PAK 2017/06/28 2017/06/28 DESCENDING            5.0     -19.56          28   False        False
  7  Paraguay    Paraguay    PRY 2018/10/31 2018/10/31 DESCENDING           68.0     -19.94          67   False        False
  8   Somalia     Somalia    SOM 2018/05/07 2018/05/05  ASCENDING          116.0     -21.06          26    True         True
  9     Spain       Spain    ESP 2019/09/17 2019/09/18 DESCENDING          110.0     -25.13          30   False        False
 10 Sri-Lanka   Sri-Lanka    LKA 2017/05/30 2017/05/28 DESCENDING           19.0     -21.69          42   False        False
 11       USA         USA    USA 2019/05/22 2019/05/22  ASCENDING          136.0     -22.62          69   False        False
 12  Colombia    Colombia    COL 2018/08/22 2018/08/23  ASCENDING          106.0     -21.31           0   False        False

{'chip': 'Bolivia_379434_S1Hand', 'event': 'Bolivia', 'scene': 'S1B_IW_GRDH_1SDV_20180215T095810_20180215T095835_009632_0115DE', 'pol': 'vv', 'bias_db': 0.0005099773406982422, 'r_zero': 0.9379555998959527, 'r_best': 0.9852559481891711, 'dy': 0, 'dx': -1}
{'chip': 'Bolivia_379434_S1Hand', 'event': 'Bolivia', 'scene': 'S1B_IW_GRDH_1SDV_20180215T095810_20180215T095835_009632_0115DE', 'pol': 'vh', 'bias_db': 0.0008544921875, 'r_zero': 0.9230866240103885, 'r_best': 0.9813250962797162, 'dy': 0, 'dx': -1}

{'chip': 'Bolivia_314919_S1Hand', 'event': 'Bolivia', 'scene': 'S1B_IW_GRDH_1SDV_20180215T095745_20180215T095810_009632_0115DE', 'pol': 'vv', 'bias_db': 0.005013227462768555, 'r_zero': 0.9865232266274121, 'r_best': 0.993768633947548, 'dy': 0, 'dx': -1}
{'chip': 'Bolivia_314919_S1Hand', 'event': 'Bolivia', 'scene': 'S1B_IW_GRDH_1SDV_20180215T095745_20180215T095810_009632_0115DE', 'pol': 'vh', 'bias_db': 0.0021867752075195312, 'r_zero': 0.9825277354316508, 'r_best': 0.9913017031131497, 'dy': 0, 'dx': -1}

{'chip': 'Ghana_154838_S1Hand', 'event': 'Ghana', 'scene': 'S1B_IW_GRDH_1SDV_20180918T181808_20180918T181833_012773_017943', 'pol': 'vv', 'bias_db': -0.0012888908386230469, 'r_zero': 0.9646655244743576, 'r_best': 0.964867474865579, 'dy': 0, 'dx': 0}
{'chip': 'Ghana_154838_S1Hand', 'event': 'Ghana', 'scene': 'S1B_IW_GRDH_1SDV_20180918T181808_20180918T181833_012773_017943', 'pol': 'vh', 'bias_db': 0.0013327598571777344, 'r_zero': 0.9565587997800278, 'r_best': 0.9567436978985133, 'dy': 0, 'dx': 0}

{'chip': 'Ghana_146222_S1Hand', 'event': 'Ghana', 'scene': 'S1B_IW_GRDH_1SDV_20180918T181808_20180918T181833_012773_017943', 'pol': 'vv', 'bias_db': -0.000759124755859375, 'r_zero': 0.9350685458227521, 'r_best': 0.9351441597130734, 'dy': 0, 'dx': 0}
{'chip': 'Ghana_146222_S1Hand', 'event': 'Ghana', 'scene': 'S1B_IW_GRDH_1SDV_20180918T181808_20180918T181833_012773_017943', 'pol': 'vh', 'bias_db': -0.00019216537475585938, 'r_zero': 0.9317224732959942, 'r_best': 0.9320917636182178, 'dy': 0, 'dx': 0}

{'chip': 'India_1018317_S1Hand', 'event': 'India', 'scene': 'S1A_IW_GRDH_1SDV_20160812T234622_20160812T234651_012574_013B43', 'pol': 'vv', 'bias_db': -0.004265308380126953, 'r_zero': 0.9817898047581329, 'r_best': 0.9921583993532286, 'dy': 0, 'dx': -1}
{'chip': 'India_1018317_S1Hand', 'event': 'India', 'scene': 'S1A_IW_GRDH_1SDV_20160812T234622_20160812T234651_012574_013B43', 'pol': 'vh', 'bias_db': -0.01067352294921875, 'r_zero': 0.9457521362754866, 'r_best': 0.9768772752003451, 'dy': 0, 'dx': -1}

{'chip': 'India_1068117_S1Hand', 'event': 'India', 'scene': 'S1A_IW_GRDH_1SDV_20160812T234622_20160812T234651_012574_013B43', 'pol': 'vv', 'bias_db': 0.011108160018920898, 'r_zero': 0.9829159037318276, 'r_best': 0.9828963316730037, 'dy': 0, 'dx': 0}
{'chip': 'India_1068117_S1Hand', 'event': 'India', 'scene': 'S1A_IW_GRDH_1SDV_20160812T234622_20160812T234651_012574_013B43', 'pol': 'vh', 'bias_db': 0.012713432312011719, 'r_zero': 0.976755110582442, 'r_best': 0.9767239926873638, 'dy': 0, 'dx': 0}

{'chip': 'Mekong_52610_S1Hand', 'event': 'Cambodia', 'scene': 'S1B_IW_GRDH_1SDV_20180805T111057_20180805T111127_012127_016547', 'pol': 'vv', 'bias_db': -0.001739501953125, 'r_zero': 0.8686099287260026, 'r_best': 0.9866592958728044, 'dy': 0, 'dx': 3}
{'chip': 'Mekong_52610_S1Hand', 'event': 'Cambodia', 'scene': 'S1B_IW_GRDH_1SDV_20180805T111057_20180805T111127_012127_016547', 'pol': 'vh', 'bias_db': -0.02258014678955078, 'r_zero': 0.8543879139811746, 'r_best': 0.9840759689086652, 'dy': 0, 'dx': 3}

{'chip': 'Mekong_382276_S1Hand', 'event': 'Cambodia', 'scene': 'S1B_IW_GRDH_1SDV_20180805T111057_20180805T111127_012127_016547', 'pol': 'vv', 'bias_db': -0.011771202087402344, 'r_zero': 0.884110843290555, 'r_best': 0.9772483203045791, 'dy': 0, 'dx': 2}
{'chip': 'Mekong_382276_S1Hand', 'event': 'Cambodia', 'scene': 'S1B_IW_GRDH_1SDV_20180805T111057_20180805T111127_012127_016547', 'pol': 'vh', 'bias_db': -0.0028176307678222656, 'r_zero': 0.881008256765982, 'r_best': 0.9763435434170362, 'dy': 0, 'dx': 2}

{'chip': 'Nigeria_529525_S1Hand', 'event': 'Nigeria', 'scene': 'S1A_IW_GRDH_1SDV_20180921T175357_20180921T175422_023800_0298AE', 'pol': 'vv', 'bias_db': -0.0052661895751953125, 'r_zero': 0.9897467442475326, 'r_best': 0.9897621778891095, 'dy': 0, 'dx': 0}
{'chip': 'Nigeria_529525_S1Hand', 'event': 'Nigeria', 'scene': 'S1A_IW_GRDH_1SDV_20180921T175357_20180921T175422_023800_0298AE', 'pol': 'vh', 'bias_db': -0.012400627136230469, 'r_zero': 0.9884197571072187, 'r_best': 0.9884788709800018, 'dy': 0, 'dx': 0}

{'chip': 'Nigeria_600295_S1Hand', 'event': 'Nigeria', 'scene': 'S1A_IW_GRDH_1SDV_20180921T175357_20180921T175422_023800_0298AE', 'pol': 'vv', 'bias_db': 0.0020012855529785156, 'r_zero': 0.9956473468936508, 'r_best': 0.9956811037680975, 'dy': 0, 'dx': 0}
{'chip': 'Nigeria_600295_S1Hand', 'event': 'Nigeria', 'scene': 'S1A_IW_GRDH_1SDV_20180921T175357_20180921T175422_023800_0298AE', 'pol': 'vh', 'bias_db': -0.003647327423095703, 'r_zero': 0.993911533284606, 'r_best': 0.9939282994626899, 'dy': 0, 'dx': 0}

{'chip': 'Somalia_685158_S1Hand', 'event': 'Somalia', 'scene': 'S1B_IW_GRDH_1SDV_20180507T151511_20180507T151540_010817_013C63', 'pol': 'vv', 'bias_db': -0.0006093978881835938, 'r_zero': 0.9872577914244972, 'r_best': 0.9873006965406083, 'dy': 0, 'dx': 0}
{'chip': 'Somalia_685158_S1Hand', 'event': 'Somalia', 'scene': 'S1B_IW_GRDH_1SDV_20180507T151511_20180507T151540_010817_013C63', 'pol': 'vh', 'bias_db': 9.393692016601562e-05, 'r_zero': 0.9887285193478322, 'r_best': 0.9888989729119416, 'dy': 0, 'dx': 0}

{'chip': 'Somalia_886726_S1Hand', 'event': 'Somalia', 'scene': 'S1B_IW_GRDH_1SDV_20180507T151540_20180507T151605_010817_013C63', 'pol': 'vv', 'bias_db': 7.343292236328125e-05, 'r_zero': 0.9892287985960807, 'r_best': 0.9893241587437513, 'dy': 0, 'dx': 0}
{'chip': 'Somalia_886726_S1Hand', 'event': 'Somalia', 'scene': 'S1B_IW_GRDH_1SDV_20180507T151540_20180507T151605_010817_013C63', 'pol': 'vh', 'bias_db': -0.0020661354064941406, 'r_zero': 0.9865960453864147, 'r_best': 0.9867052210075373, 'dy': 0, 'dx': 0}

{'chip': 'Spain_5678382_S1Hand', 'event': 'Spain', 'scene': 'S1A_IW_GRDH_1SDV_20190917T060222_20190917T060247_029057_034C21', 'pol': 'vv', 'bias_db': 0.040618896484375, 'r_zero': 0.9773976258907707, 'r_best': 0.9772790451847018, 'dy': 0, 'dx': 0}
{'chip': 'Spain_5678382_S1Hand', 'event': 'Spain', 'scene': 'S1A_IW_GRDH_1SDV_20190917T060222_20190917T060247_029057_034C21', 'pol': 'vh', 'bias_db': 0.042894840240478516, 'r_zero': 0.9750694480752244, 'r_best': 0.9750686110197279, 'dy': 0, 'dx': 0}

{'chip': 'Spain_8104659_S1Hand', 'event': 'Spain', 'scene': 'S1A_IW_GRDH_1SDV_20190917T060222_20190917T060247_029057_034C21', 'pol': 'vv', 'bias_db': 0.03087615966796875, 'r_zero': 0.9603084392965668, 'r_best': 0.9604231226684498, 'dy': 0, 'dx': 0}
{'chip': 'Spain_8104659_S1Hand', 'event': 'Spain', 'scene': 'S1A_IW_GRDH_1SDV_20190917T060222_20190917T060247_029057_034C21', 'pol': 'vh', 'bias_db': 0.028969764709472656, 'r_zero': 0.9635710207360307, 'r_best': 0.96395956168946, 'dy': 0, 'dx': 0}

{'chip': 'Sri-Lanka_1038087_S1Hand', 'event': 'Sri-Lanka', 'scene': 'S1B_IW_GRDH_1SDV_20170530T002405_20170530T002430_005820_00A340', 'pol': 'vv', 'bias_db': 0.01130533218383789, 'r_zero': 0.9681444474585721, 'r_best': 0.9679539175216934, 'dy': 0, 'dx': 0}
{'chip': 'Sri-Lanka_1038087_S1Hand', 'event': 'Sri-Lanka', 'scene': 'S1B_IW_GRDH_1SDV_20170530T002405_20170530T002430_005820_00A340', 'pol': 'vh', 'bias_db': 0.010416030883789062, 'r_zero': 0.9796293977496094, 'r_best': 0.9796224691284394, 'dy': 0, 'dx': 0}

{'chip': 'Sri-Lanka_748447_S1Hand', 'event': 'Sri-Lanka', 'scene': 'S1B_IW_GRDH_1SDV_20170530T002430_20170530T002501_005820_00A340', 'pol': 'vv', 'bias_db': 0.018342018127441406, 'r_zero': 0.9023796042532201, 'r_best': 0.965029606590737, 'dy': 0, 'dx': -1}
{'chip': 'Sri-Lanka_748447_S1Hand', 'event': 'Sri-Lanka', 'scene': 'S1B_IW_GRDH_1SDV_20170530T002430_20170530T002501_005820_00A340', 'pol': 'vh', 'bias_db': 0.018082618713378906, 'r_zero': 0.9035365582098767, 'r_best': 0.9650995354451191, 'dy': 0, 'dx': -1}

{'chip': 'USA_19225_S1Hand', 'event': 'USA', 'scene': 'S1A_IW_GRDH_1SDV_20190522T002101_20190522T002126_027333_031530', 'pol': 'vv', 'bias_db': 0.011579513549804688, 'r_zero': 0.9798620402836961, 'r_best': 0.9799887260144949, 'dy': 0, 'dx': 0}
{'chip': 'USA_19225_S1Hand', 'event': 'USA', 'scene': 'S1A_IW_GRDH_1SDV_20190522T002101_20190522T002126_027333_031530', 'pol': 'vh', 'bias_db': 0.009243965148925781, 'r_zero': 0.9732807027641457, 'r_best': 0.9732496397484732, 'dy': 0, 'dx': 0}

{'chip': 'USA_788696_S1Hand', 'event': 'USA', 'scene': 'S1A_IW_GRDH_1SDV_20190522T002101_20190522T002126_027333_031530', 'pol': 'vv', 'bias_db': 0.006886482238769531, 'r_zero': 0.995568155682349, 'r_best': 0.9955842667321073, 'dy': 0, 'dx': 0}
{'chip': 'USA_788696_S1Hand', 'event': 'USA', 'scene': 'S1A_IW_GRDH_1SDV_20190522T002101_20190522T002126_027333_031530', 'pol': 'vh', 'bias_db': 0.002178192138671875, 'r_zero': 0.9943800743854994, 'r_best': 0.9943700593924983, 'dy': 0, 'dx': 0}
pol                   vh         vv
bias_db count  18.000000  18.000000
        mean    0.004144   0.006256
        std     0.015084   0.013032
        min    -0.022580  -0.011771
        25%    -0.002630  -0.001156
        50%     0.001094   0.001256
        75%     0.010123   0.011256
        max     0.042895   0.040619
r_zero  count  18.000000  18.000000
        mean    0.955496   0.960399
        std     0.041199   0.039140
        min     0.854388   0.868610
        25%     0.935230   0.943544
        50%     0.974175   0.978630
        75%     0.985579   0.987074
        max     0.994380   0.995647
r_best  count  18.000000  18.000000
        mean    0.976937   0.979240
        std     0.015326   0.015606
        min     0.932092   0.935144
        25%     0.973704   0.970278
        50%     0.978250   0.984076
        75%     0.988035   0.989653
        max     0.994370   0.995681

## 4. Pre-event chips and U-Net training

Pre-event chips for the hand-labelled set, then training. The paper's weights were trained on Kaggle with `kaggle/unet_main` and `kaggle/unet_pre`.

In [5]:
import json, subprocess
import pre_event_chips
from config import MODELS, CACHE

pre_event_chips.main()
if TRAIN_LOCALLY:
    subprocess.run([sys.executable, 'train_unet.py', '--data', str(CACHE / 'sen1floods11'),
                    '--pre-dir', str(pre_event_chips.OUT), '--out', str(MODELS)], cwd=ROOT / 'pipeline', check=True)
results = json.loads((MODELS / 'sen1floods11_results.json').read_text())
pd.DataFrame({run: {f'{split} {kind}': v[split][kind]['mean_chip_iou']
                    for split in ('test', 'bolivia', 'test_paired', 'bolivia_paired') if split in v
                    for kind in ('all_water', 'flood_water')} for run, v in results.items()}).round(3)

{'chip': 'Bolivia_103757', 'event_date': '2018/02/15', 'pre_id': 'S1B_IW_GRDH_1SDV_20180110T095746_20180110T095811_009107_0104AA', 'pre_date': '2018-01-10'}

{'chip': 'Bolivia_129334', 'event_date': '2018/02/15', 'pre_id': None, 'pre_date': None}

{'chip': 'Bolivia_195474', 'event_date': '2018/02/15', 'pre_id': 'S1B_IW_GRDH_1SDV_20180110T095811_20180110T095836_009107_0104AA', 'pre_date': '2018-01-10'}

{'chip': 'Bolivia_23014', 'event_date': '2018/02/15', 'pre_id': None, 'pre_date': None}

{'chip': 'Bolivia_233925', 'event_date': '2018/02/15', 'pre_id': None, 'pre_date': None}

{'chip': 'Bolivia_242570', 'event_date': '2018/02/15', 'pre_id': None, 'pre_date': None}

{'chip': 'Bolivia_290290', 'event_date': '2018/02/15', 'pre_id': 'S1B_IW_GRDH_1SDV_20180110T095746_20180110T095811_009107_0104AA', 'pre_date': '2018-01-10'}

{'chip': 'Bolivia_294583', 'event_date': '2018/02/15', 'pre_id': 'S1B_IW_GRDH_1SDV_20180110T095721_20180110T095746_009107_0104AA', 'pre_date': '2018-01-10'}

{'chip': 'Bolivia_312675', 'event_date': '2018/02/15', 'pre_id': 'S1B_IW_GRDH_1SDV_20180110T095811_20180110T095836_009107_0104AA', 'pre_date': '2018-01-10'}

{'chip': 'Bolivia_314919', 'event_date': '2018/02/15', 'pre_id': 'S1B_IW_GRDH_1SDV_20180110T095746_20180110T095811_009107_0104AA', 'pre_date': '2018-01-10'}

{'chip': 'Bolivia_360519', 'event_date': '2018/02/15', 'pre_id': None, 'pre_date': None}

{'chip': 'Bolivia_379434', 'event_date': '2018/02/15', 'pre_id': 'S1B_IW_GRDH_1SDV_20180110T095811_20180110T095836_009107_0104AA', 'pre_date': '2018-01-10'}

{'chip': 'Bolivia_432776', 'event_date': '2018/02/15', 'pre_id': None, 'pre_date': None}

{'chip': 'Bolivia_60373', 'event_date': '2018/02/15', 'pre_id': 'S1B_IW_GRDH_1SDV_20180110T095746_20180110T095811_009107_0104AA', 'pre_date': '2018-01-10'}

{'chip': 'Bolivia_76104', 'event_date': '2018/02/15', 'pre_id': 'S1B_IW_GRDH_1SDV_20180110T095721_20180110T095746_009107_0104AA', 'pre_date': '2018-01-10'}

{'chip': 'Ghana_103272', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181850_20180819T181915_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_1033830', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181850_20180819T181915_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_1078550', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181915_20180819T181940_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_1089161', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181915_20180819T181940_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_11745', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181915_20180819T181940_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_124834', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181915_20180819T181940_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_128663', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181850_20180819T181915_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_132163', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181850_20180819T181915_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_134751', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181850_20180819T181915_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_135389', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181915_20180819T181940_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_141271', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181915_20180819T181940_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_141910', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181915_20180819T181940_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_142312', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181915_20180819T181940_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_144050', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181915_20180819T181940_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_146222', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181850_20180819T181915_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_147015', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181915_20180819T181940_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_154838', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181850_20180819T181915_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_156478', 'event_date': '2018/09/18', 'pre_id': 'S1B_IW_GRDH_1SDV_20180813T181831_20180813T181907_012248_016915', 'pre_date': '2018-08-13'}

{'chip': 'Ghana_161233', 'event_date': '2018/09/18', 'pre_id': None, 'pre_date': None}

{'chip': 'Ghana_167233', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181915_20180819T181940_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_168875', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181850_20180819T181915_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_187318', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181915_20180819T181940_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_194723', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181850_20180819T181915_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_234935', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181850_20180819T181915_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_247288', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181850_20180819T181915_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_24858', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181915_20180819T181940_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_26376', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181850_20180819T181915_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_264787', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181850_20180819T181915_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_277', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181850_20180819T181915_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_308249', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181915_20180819T181940_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_313799', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181850_20180819T181915_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_319168', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181850_20180819T181915_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_359826', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181915_20180819T181940_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_362274', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181915_20180819T181940_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_406026', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181915_20180819T181940_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_45911', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181850_20180819T181915_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_495107', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181915_20180819T181940_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_49890', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181915_20180819T181940_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_5079', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181850_20180819T181915_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_53713', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181915_20180819T181940_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_597288', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181915_20180819T181940_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_61925', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181915_20180819T181940_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_7496', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181850_20180819T181915_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_8090', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181850_20180819T181915_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_83200', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181850_20180819T181915_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_83483', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181850_20180819T181915_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_866994', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181850_20180819T181915_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_868803', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181915_20180819T181940_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_887131', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181915_20180819T181940_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_895194', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181850_20180819T181915_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_953791', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181915_20180819T181940_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_97059', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181850_20180819T181915_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'Ghana_97516', 'event_date': '2018/09/18', 'pre_id': 'S1A_IW_GRDH_1SDV_20180819T181915_20180819T181940_023319_028941', 'pre_date': '2018-08-19'}

{'chip': 'India_1017769', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_1018317', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_1018327', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_103447', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_1050276', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_1068117', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_1072277', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_118868', 'event_date': '2016/08/12', 'pre_id': None, 'pre_date': None}

{'chip': 'India_135434', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_136196', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_164336', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_166709', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_177319', 'event_date': '2016/08/12', 'pre_id': None, 'pre_date': None}

{'chip': 'India_179238', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_180633', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_207862', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_244057', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_25540', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_265762', 'event_date': '2016/08/12', 'pre_id': None, 'pre_date': None}

{'chip': 'India_273873', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_285297', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_287642', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_324254', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_373039', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_383430', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_391908', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_399883', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_44475', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_500266', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_533192', 'event_date': '2016/08/12', 'pre_id': None, 'pre_date': None}

{'chip': 'India_534470', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_56450', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_566697', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_570384', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_591317', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_591549', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_592446', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_59460', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_624341', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_631692', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_652725', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_664410', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_691027', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_698338', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_70352', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_707886', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_73419', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_747970', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_747992', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_764946', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_769408', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_772630', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_773682', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_774689', 'event_date': '2016/08/12', 'pre_id': None, 'pre_date': None}

{'chip': 'India_79637', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_80221', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_804466', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_828067', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_833266', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_842775', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_869358', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_900498', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_91379', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_943439', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_952728', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234618_20160601T234647_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_956930', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_979278', 'event_date': '2016/08/12', 'pre_id': 'S1A_IW_GRDH_1SDV_20160601T234647_20160601T234712_011524_01195C', 'pre_date': '2016-06-01'}

{'chip': 'India_981708', 'event_date': '2016/08/12', 'pre_id': None, 'pre_date': None}

{'chip': 'Mekong_1111068', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111056_20180630T111125_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Mekong_1149855', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111056_20180630T111125_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Mekong_1191208', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111125_20180630T111150_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Mekong_119477', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111056_20180630T111125_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Mekong_1248200', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111056_20180630T111125_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Mekong_1282475', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111056_20180630T111125_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Mekong_1395593', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111056_20180630T111125_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Mekong_1396181', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111056_20180630T111125_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Mekong_1413877', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111056_20180630T111125_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Mekong_1439641', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111056_20180630T111125_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Mekong_1443339', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111056_20180630T111125_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Mekong_16233', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111056_20180630T111125_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Mekong_213094', 'event_date': '2018/08/05', 'pre_id': 'S1A_IW_GRDH_1SDV_20180624T111144_20180624T111209_022498_026FCE', 'pre_date': '2018-06-24'}

{'chip': 'Mekong_221789', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111125_20180630T111150_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Mekong_254910', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111056_20180630T111125_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Mekong_269835', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111056_20180630T111125_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Mekong_293769', 'event_date': '2018/08/05', 'pre_id': 'S1A_IW_GRDH_1SDV_20180624T111144_20180624T111209_022498_026FCE', 'pre_date': '2018-06-24'}

{'chip': 'Mekong_333434', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111125_20180630T111150_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Mekong_342411', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111056_20180630T111125_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Mekong_382276', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111056_20180630T111125_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Mekong_424793', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111056_20180630T111125_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Mekong_45934', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111056_20180630T111125_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Mekong_474783', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111056_20180630T111125_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Mekong_52610', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111056_20180630T111125_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Mekong_596495', 'event_date': '2018/08/05', 'pre_id': 'S1A_IW_GRDH_1SDV_20180624T111144_20180624T111209_022498_026FCE', 'pre_date': '2018-06-24'}

{'chip': 'Mekong_774566', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111125_20180630T111150_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Mekong_846007', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111056_20180630T111125_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Mekong_922373', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111056_20180630T111125_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Mekong_977338', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111125_20180630T111150_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Mekong_98310', 'event_date': '2018/08/05', 'pre_id': 'S1B_IW_GRDH_1SDV_20180630T111125_20180630T111150_011602_01553E', 'pre_date': '2018-06-30'}

{'chip': 'Nigeria_1095404', 'event_date': '2018/09/21', 'pre_id': 'S1A_IW_GRDH_1SDV_20180816T175356_20180816T175421_023275_0287D4', 'pre_date': '2018-08-16'}

{'chip': 'Nigeria_143329', 'event_date': '2018/09/21', 'pre_id': 'S1A_IW_GRDH_1SDV_20180816T175421_20180816T175446_023275_0287D4', 'pre_date': '2018-08-16'}

{'chip': 'Nigeria_22088', 'event_date': '2018/09/21', 'pre_id': None, 'pre_date': None}

{'chip': 'Nigeria_225131', 'event_date': '2018/09/21', 'pre_id': 'S1A_IW_GRDH_1SDV_20180816T175421_20180816T175446_023275_0287D4', 'pre_date': '2018-08-16'}

{'chip': 'Nigeria_31096', 'event_date': '2018/09/21', 'pre_id': 'S1A_IW_GRDH_1SDV_20180816T175356_20180816T175421_023275_0287D4', 'pre_date': '2018-08-16'}

{'chip': 'Nigeria_35845', 'event_date': '2018/09/21', 'pre_id': 'S1A_IW_GRDH_1SDV_20180816T175356_20180816T175421_023275_0287D4', 'pre_date': '2018-08-16'}

{'chip': 'Nigeria_417184', 'event_date': '2018/09/21', 'pre_id': None, 'pre_date': None}

{'chip': 'Nigeria_439488', 'event_date': '2018/09/21', 'pre_id': 'S1A_IW_GRDH_1SDV_20180816T175356_20180816T175421_023275_0287D4', 'pre_date': '2018-08-16'}

{'chip': 'Nigeria_529525', 'event_date': '2018/09/21', 'pre_id': 'S1A_IW_GRDH_1SDV_20180816T175356_20180816T175421_023275_0287D4', 'pre_date': '2018-08-16'}

{'chip': 'Nigeria_598959', 'event_date': '2018/09/21', 'pre_id': 'S1A_IW_GRDH_1SDV_20180816T175356_20180816T175421_023275_0287D4', 'pre_date': '2018-08-16'}

{'chip': 'Nigeria_600295', 'event_date': '2018/09/21', 'pre_id': 'S1A_IW_GRDH_1SDV_20180816T175356_20180816T175421_023275_0287D4', 'pre_date': '2018-08-16'}

{'chip': 'Nigeria_707067', 'event_date': '2018/09/21', 'pre_id': 'S1A_IW_GRDH_1SDV_20180816T175421_20180816T175446_023275_0287D4', 'pre_date': '2018-08-16'}

{'chip': 'Nigeria_78061', 'event_date': '2018/09/21', 'pre_id': 'S1A_IW_GRDH_1SDV_20180816T175356_20180816T175421_023275_0287D4', 'pre_date': '2018-08-16'}

{'chip': 'Nigeria_812045', 'event_date': '2018/09/21', 'pre_id': None, 'pre_date': None}

{'chip': 'Nigeria_81933', 'event_date': '2018/09/21', 'pre_id': 'S1A_IW_GRDH_1SDV_20180816T175356_20180816T175421_023275_0287D4', 'pre_date': '2018-08-16'}

{'chip': 'Nigeria_820924', 'event_date': '2018/09/21', 'pre_id': 'S1A_IW_GRDH_1SDV_20180816T175421_20180816T175446_023275_0287D4', 'pre_date': '2018-08-16'}

{'chip': 'Nigeria_952958', 'event_date': '2018/09/21', 'pre_id': 'S1A_IW_GRDH_1SDV_20180816T175356_20180816T175421_023275_0287D4', 'pre_date': '2018-08-16'}

{'chip': 'Nigeria_984831', 'event_date': '2018/09/21', 'pre_id': 'S1A_IW_GRDH_1SDV_20180816T175356_20180816T175421_023275_0287D4', 'pre_date': '2018-08-16'}

{'chip': 'Pakistan_1027214', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011632_20170523T011657_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Pakistan_1036366', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011632_20170523T011657_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Pakistan_132143', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011542_20170523T011607_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Pakistan_167553', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011607_20170523T011632_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Pakistan_210595', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011517_20170523T011542_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Pakistan_211386', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011607_20170523T011632_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Pakistan_246510', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011607_20170523T011632_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Pakistan_246718', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011607_20170523T011632_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Pakistan_336228', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011607_20170523T011632_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Pakistan_35915', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011632_20170523T011657_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Pakistan_366265', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011517_20170523T011542_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Pakistan_401863', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011517_20170523T011542_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Pakistan_43105', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170228T011522_20170228T011547_015477_0196AF', 'pre_date': '2017-02-28'}

{'chip': 'Pakistan_474121', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011517_20170523T011542_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Pakistan_528249', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011632_20170523T011657_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Pakistan_548910', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011607_20170523T011632_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Pakistan_65724', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011542_20170523T011607_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Pakistan_664885', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011517_20170523T011542_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Pakistan_667363', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011517_20170523T011542_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Pakistan_694942', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011517_20170523T011542_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Pakistan_70625', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011542_20170523T011607_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Pakistan_712873', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011607_20170523T011632_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Pakistan_740461', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011542_20170523T011607_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Pakistan_760290', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011517_20170523T011542_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Pakistan_849790', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011542_20170523T011607_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Pakistan_909806', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011607_20170523T011632_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Pakistan_94095', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011607_20170523T011632_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Pakistan_9684', 'event_date': '2017/06/28', 'pre_id': 'S1A_IW_GRDH_1SDV_20170523T011632_20170523T011657_016702_01BBBA', 'pre_date': '2017-05-23'}

{'chip': 'Paraguay_1019808', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_1029042', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_1029191', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_1056717', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_1076204', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_11869', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_126224', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091156_20180925T091221_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_12870', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_148318', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_149787', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_149830', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091156_20180925T091221_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_153941', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091106_20180925T091131_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_172476', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091156_20180925T091221_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_179624', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091106_20180925T091131_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_191503', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_198534', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_205585', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_212687', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091156_20180925T091221_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_215904', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_224845', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_225187', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_232281', 'event_date': '2018/10/31', 'pre_id': None, 'pre_date': None}

{'chip': 'Paraguay_24341', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_246154', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_247656', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_252217', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_271769', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_280900', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_284928', 'event_date': '2018/10/31', 'pre_id': None, 'pre_date': None}

{'chip': 'Paraguay_305760', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_339807', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_34417', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_36015', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_36146', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_403081', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_40936', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_44682', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_470303', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091156_20180925T091221_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_482517', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_48673', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091106_20180925T091131_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_511199', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091156_20180925T091221_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_54421', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_581976', 'event_date': '2018/10/31', 'pre_id': None, 'pre_date': None}

{'chip': 'Paraguay_59731', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_605682', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_62897', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_648632', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_651904', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_657443', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_683296', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_721886', 'event_date': '2018/10/31', 'pre_id': None, 'pre_date': None}

{'chip': 'Paraguay_76868', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_7894', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091156_20180925T091221_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_790830', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_791364', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_792268', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091156_20180925T091221_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_795075', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_80102', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_822142', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091156_20180925T091221_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_868895', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_892933', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_896458', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_913449', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_921838', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_934240', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_989230', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091156_20180925T091221_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Paraguay_997480', 'event_date': '2018/10/31', 'pre_id': 'S1B_IW_GRDH_1SDV_20180925T091131_20180925T091156_012869_017C37', 'pre_date': '2018-09-25'}

{'chip': 'Somalia_1068756', 'event_date': '2018/05/07', 'pre_id': None, 'pre_date': None}

{'chip': 'Somalia_1087508', 'event_date': '2018/05/07', 'pre_id': 'S1B_IW_GRDH_1SDV_20180401T151509_20180401T151538_010292_012B81', 'pre_date': '2018-04-01'}

{'chip': 'Somalia_12849', 'event_date': '2018/05/07', 'pre_id': 'S1B_IW_GRDH_1SDV_20180401T151509_20180401T151538_010292_012B81', 'pre_date': '2018-04-01'}

{'chip': 'Somalia_166342', 'event_date': '2018/05/07', 'pre_id': 'S1B_IW_GRDH_1SDV_20180401T151538_20180401T151603_010292_012B81', 'pre_date': '2018-04-01'}

{'chip': 'Somalia_167787', 'event_date': '2018/05/07', 'pre_id': 'S1B_IW_GRDH_1SDV_20180401T151509_20180401T151538_010292_012B81', 'pre_date': '2018-04-01'}

{'chip': 'Somalia_195014', 'event_date': '2018/05/07', 'pre_id': 'S1B_IW_GRDH_1SDV_20180401T151538_20180401T151603_010292_012B81', 'pre_date': '2018-04-01'}

{'chip': 'Somalia_205466', 'event_date': '2018/05/07', 'pre_id': 'S1B_IW_GRDH_1SDV_20180401T151538_20180401T151603_010292_012B81', 'pre_date': '2018-04-01'}

{'chip': 'Somalia_230192', 'event_date': '2018/05/07', 'pre_id': 'S1B_IW_GRDH_1SDV_20180401T151509_20180401T151538_010292_012B81', 'pre_date': '2018-04-01'}

{'chip': 'Somalia_256539', 'event_date': '2018/05/07', 'pre_id': 'S1B_IW_GRDH_1SDV_20180401T151509_20180401T151538_010292_012B81', 'pre_date': '2018-04-01'}

{'chip': 'Somalia_295782', 'event_date': '2018/05/07', 'pre_id': 'S1B_IW_GRDH_1SDV_20180401T151509_20180401T151538_010292_012B81', 'pre_date': '2018-04-01'}

{'chip': 'Somalia_322855', 'event_date': '2018/05/07', 'pre_id': 'S1B_IW_GRDH_1SDV_20180401T151509_20180401T151538_010292_012B81', 'pre_date': '2018-04-01'}

{'chip': 'Somalia_32375', 'event_date': '2018/05/07', 'pre_id': None, 'pre_date': None}

{'chip': 'Somalia_371421', 'event_date': '2018/05/07', 'pre_id': 'S1B_IW_GRDH_1SDV_20180401T151538_20180401T151603_010292_012B81', 'pre_date': '2018-04-01'}

{'chip': 'Somalia_60129', 'event_date': '2018/05/07', 'pre_id': 'S1B_IW_GRDH_1SDV_20180401T151538_20180401T151603_010292_012B81', 'pre_date': '2018-04-01'}

{'chip': 'Somalia_61368', 'event_date': '2018/05/07', 'pre_id': 'S1B_IW_GRDH_1SDV_20180401T151538_20180401T151603_010292_012B81', 'pre_date': '2018-04-01'}

{'chip': 'Somalia_626316', 'event_date': '2018/05/07', 'pre_id': 'S1B_IW_GRDH_1SDV_20180401T151509_20180401T151538_010292_012B81', 'pre_date': '2018-04-01'}

{'chip': 'Somalia_649376', 'event_date': '2018/05/07', 'pre_id': 'S1B_IW_GRDH_1SDV_20180401T151509_20180401T151538_010292_012B81', 'pre_date': '2018-04-01'}

{'chip': 'Somalia_685158', 'event_date': '2018/05/07', 'pre_id': 'S1B_IW_GRDH_1SDV_20180401T151509_20180401T151538_010292_012B81', 'pre_date': '2018-04-01'}

{'chip': 'Somalia_699062', 'event_date': '2018/05/07', 'pre_id': 'S1B_IW_GRDH_1SDV_20180401T151509_20180401T151538_010292_012B81', 'pre_date': '2018-04-01'}

{'chip': 'Somalia_7931', 'event_date': '2018/05/07', 'pre_id': 'S1B_IW_GRDH_1SDV_20180401T151538_20180401T151603_010292_012B81', 'pre_date': '2018-04-01'}

{'chip': 'Somalia_886726', 'event_date': '2018/05/07', 'pre_id': 'S1B_IW_GRDH_1SDV_20180401T151538_20180401T151603_010292_012B81', 'pre_date': '2018-04-01'}

{'chip': 'Somalia_93023', 'event_date': '2018/05/07', 'pre_id': 'S1B_IW_GRDH_1SDV_20180401T151509_20180401T151538_010292_012B81', 'pre_date': '2018-04-01'}

{'chip': 'Somalia_94102', 'event_date': '2018/05/07', 'pre_id': 'S1B_IW_GRDH_1SDV_20180401T151538_20180401T151603_010292_012B81', 'pre_date': '2018-04-01'}

{'chip': 'Somalia_970508', 'event_date': '2018/05/07', 'pre_id': 'S1B_IW_GRDH_1SDV_20180401T151538_20180401T151603_010292_012B81', 'pre_date': '2018-04-01'}

{'chip': 'Somalia_989553', 'event_date': '2018/05/07', 'pre_id': 'S1B_IW_GRDH_1SDV_20180401T151603_20180401T151628_010292_012B81', 'pre_date': '2018-04-01'}

{'chip': 'Somalia_992457', 'event_date': '2018/05/07', 'pre_id': 'S1B_IW_GRDH_1SDV_20180401T151509_20180401T151538_010292_012B81', 'pre_date': '2018-04-01'}

{'chip': 'Spain_1167260', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_1199913', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_2472849', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_2523247', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_2594119', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_2938657', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_3285448', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_337094', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_4282030', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_4915752', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_5650136', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_5678382', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_5816638', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_5923267', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_6095801', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_6199994', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_6537196', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_6860600', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_716716', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_7370579', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_7387658', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_7558720', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_7604243', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_7786924', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_7856615', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_8104659', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_8154154', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_8199661', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_8372658', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Spain_8565131', 'event_date': '2019/09/17', 'pre_id': 'S1B_IW_GRDH_1SDV_20190818T060140_20190818T060205_017636_0212DC;S1B_IW_GRDH_1SDV_20190818T060139_20190818T060204_017636_0212DC', 'pre_date': '2019-08-18'}

{'chip': 'Sri-Lanka_101973', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002445_20170418T002510_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_1038087', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002445_20170418T002510_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_1049830', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002510_20170418T002536_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_117737', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002445_20170418T002510_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_120804', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002445_20170418T002510_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_132922', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002445_20170418T002510_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_135713', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002510_20170418T002536_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_14484', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002510_20170418T002536_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_152185', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002445_20170418T002510_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_163406', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002445_20170418T002510_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_178753', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002510_20170418T002536_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_233609', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002445_20170418T002510_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_236030', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002510_20170418T002536_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_236628', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002510_20170418T002536_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_249079', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002510_20170418T002536_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_31559', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002510_20170418T002536_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_321316', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002445_20170418T002510_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_377277', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002510_20170418T002536_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_400518', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002510_20170418T002536_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_450918', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002510_20170418T002536_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_49764', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002510_20170418T002536_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_52223', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002445_20170418T002510_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_523539', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002510_20170418T002536_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_534068', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002445_20170418T002510_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_551926', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002445_20170418T002510_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_55568', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002510_20170418T002536_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_579082', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002510_20170418T002536_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_612594', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002445_20170418T002510_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_63307', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002445_20170418T002510_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_649970', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002510_20170418T002536_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_653336', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002445_20170418T002510_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_713926', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002445_20170418T002510_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_748447', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002510_20170418T002536_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_845821', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002510_20170418T002536_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_847275', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002510_20170418T002536_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_849649', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002510_20170418T002536_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_85652', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002510_20170418T002536_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_883641', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002445_20170418T002510_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_916628', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002510_20170418T002536_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_922192', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002510_20170418T002536_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_92824', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002510_20170418T002536_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'Sri-Lanka_956740', 'event_date': '2017/05/30', 'pre_id': 'S1A_IW_GRDH_1SDV_20170418T002510_20170418T002536_016191_01AC26', 'pre_date': '2017-04-18'}

{'chip': 'USA_1010394', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_1039203', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_1049586', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_1068362', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_1082482', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_11422', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_114964', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_115033', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_170264', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_179917', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_181263', 'event_date': '2019/05/22', 'pre_id': None, 'pre_date': None}

{'chip': 'USA_181503', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_19225', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_198411', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_211406', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_217598', 'event_date': '2019/05/22', 'pre_id': None, 'pre_date': None}

{'chip': 'USA_224165', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_225017', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_231124', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_232060', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_251323', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002124_20190416T002149_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_260929', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_275372', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_308150', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_347609', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_348639', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_350244', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_354981', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_366607', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_375183', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_387945', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002124_20190416T002149_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_430764', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_438959', 'event_date': '2019/05/22', 'pre_id': None, 'pre_date': None}

{'chip': 'USA_486103', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_504150', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_519181', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_527077', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_58086', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_595451', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_604222', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_605492', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_638521', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002124_20190416T002149_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_646878', 'event_date': '2019/05/22', 'pre_id': None, 'pre_date': None}

{'chip': 'USA_652955', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002124_20190416T002149_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_655230', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_66026', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002124_20190416T002149_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_664261', 'event_date': '2019/05/22', 'pre_id': None, 'pre_date': None}

{'chip': 'USA_66511', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_670826', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_67102', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_693819', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_741073', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_741178', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_758178', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_761032', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_770353', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_778194', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_788696', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_806273', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_826217', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_831672', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_84195', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_86502', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_905409', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_908474', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_933610', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_955053', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_986268', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

{'chip': 'USA_994009', 'event_date': '2019/05/22', 'pre_id': 'S1A_IW_GRDH_1SDV_20190416T002059_20190416T002124_026808_030341', 'pre_date': '2019-04-16'}

                            post_hand_weak  post_hand  pre_hand
test all_water                       0.424      0.401       NaN
test flood_water                     0.358      0.332       NaN
bolivia all_water                    0.446      0.329       NaN
bolivia flood_water                  0.392      0.306       NaN
test_paired all_water                0.424      0.404     0.409
test_paired flood_water              0.358      0.332     0.337
bolivia_paired all_water             0.446      0.346     0.431
bolivia_paired flood_water           0.392      0.322     0.410

## 5. Kenya input stacks and flood masks

In [6]:
import prepare, methods

for aoi in pd.read_csv(pick_scenes.SCENES)['aoi']:
    prepare.stack(aoi)
methods.main()

          aoi          method  threshold_db
   garissa_s2         otsu_vv    -13.666719
   garissa_s2  change_otsu_vv     -2.139417
   garissa_s2 change_fixed_vv     -3.000000
   garissa_s2         otsu_vh    -20.467318
   garissa_s2  change_otsu_vh     -1.997688
   garissa_s2 change_fixed_vh     -3.000000
   garissa_s2       unet_post           NaN
   garissa_s2  unet_post_hand           NaN
   garissa_s2        unet_pre           NaN
   garissa_pl         otsu_vv    -14.019883
   garissa_pl  change_otsu_vv     -3.504313
   garissa_pl change_fixed_vv     -3.000000
   garissa_pl         otsu_vh    -22.065986
   garissa_pl  change_otsu_vh     -5.955538
   garissa_pl change_fixed_vh     -3.000000
   garissa_pl       unet_post           NaN
   garissa_pl  unet_post_hand           NaN
   garissa_pl        unet_pre           NaN
   nairobi_pl         otsu_vv     -7.642489
   nairobi_pl  change_otsu_vv     -0.651221
   nairobi_pl change_fixed_vv     -3.000000
   nairobi_pl         otsu_vh    -18.950797
   nairobi_pl  change_otsu_vh      0.216156
   nairobi_pl change_fixed_vh     -3.000000
   nairobi_pl       unet_post           NaN
   nairobi_pl  unet_post_hand           NaN
   nairobi_pl        unet_pre           NaN
tana_420_9600         otsu_vv     -6.881602
tana_420_9600  change_otsu_vv      0.517945
tana_420_9600 change_fixed_vv     -3.000000
tana_420_9600         otsu_vh    -13.426266
tana_420_9600  change_otsu_vh      0.065766
tana_420_9600 change_fixed_vh     -3.000000
tana_420_9600       unet_post           NaN
tana_420_9600  unet_post_hand           NaN
tana_420_9600        unet_pre           NaN
tana_440_9660         otsu_vv    -10.646264
tana_440_9660  change_otsu_vv     -0.041597
tana_440_9660 change_fixed_vv     -3.000000
tana_440_9660         otsu_vh    -21.075457
tana_440_9660  change_otsu_vh      0.569712
tana_440_9660 change_fixed_vh     -3.000000
tana_440_9660       unet_post           NaN
tana_440_9660  unet_post_hand           NaN
tana_440_9660        unet_pre           NaN
tana_460_9640         otsu_vv    -15.326908
tana_460_9640  change_otsu_vv      0.032854
tana_460_9640 change_fixed_vv     -3.000000
tana_460_9640         otsu_vh    -24.260850
tana_460_9640  change_otsu_vh     -1.439623
tana_460_9640 change_fixed_vh     -3.000000
tana_460_9640       unet_post           NaN
tana_460_9640  unet_post_hand           NaN
tana_460_9640        unet_pre           NaN
tana_460_9660         otsu_vv    -13.627491
tana_460_9660  change_otsu_vv      0.074708
tana_460_9660 change_fixed_vv     -3.000000
tana_460_9660         otsu_vh    -23.263495
tana_460_9660  change_otsu_vh      0.580476
tana_460_9660 change_fixed_vh     -3.000000
tana_460_9660       unet_post           NaN
tana_460_9660  unet_post_hand           NaN
tana_460_9660        unet_pre           NaN
tana_480_9640         otsu_vv    -15.376718
tana_480_9640  change_otsu_vv      2.433502
tana_480_9640 change_fixed_vv     -3.000000
tana_480_9640         otsu_vh    -22.707463
tana_480_9640  change_otsu_vh      5.079645
tana_480_9640 change_fixed_vh     -3.000000
tana_480_9640       unet_post           NaN
tana_480_9640  unet_post_hand           NaN
tana_480_9640        unet_pre           NaN
tana_480_9660         otsu_vv    -16.615384
tana_480_9660  change_otsu_vv      1.094245
tana_480_9660 change_fixed_vv     -3.000000
tana_480_9660         otsu_vh    -26.092050
tana_480_9660  change_otsu_vh      4.998844
tana_480_9660 change_fixed_vh     -3.000000
tana_480_9660       unet_post           NaN
tana_480_9660  unet_post_hand           NaN
tana_480_9660        unet_pre           NaN
tana_500_9660         otsu_vv    -17.046807
tana_500_9660  change_otsu_vv      0.283937
tana_500_9660 change_fixed_vv     -3.000000
tana_500_9660         otsu_vh    -25.536276
tana_500_9660  change_otsu_vh      2.044051
tana_500_9660 change_fixed_vh     -3.000000
tana_500_9660       unet_post           NaN
tana_500_9660  unet_post_hand           NaN
tana_500_9660        unet_pre           NaN
tana_500_9900         otsu_vv    -10.604222
tana_500_9900  change_otsu_vv      0.801669
tana_500_9900 change_fixed_vv     -3.000000
tana_500_9900         otsu_vh    -18.318832
tana_500_9900  change_otsu_vh      1.474696
tana_500_9900 change_fixed_vh     -3.000000
tana_500_9900       unet_post           NaN
tana_500_9900  unet_post_hand           NaN
tana_500_9900        unet_pre           NaN
tana_500_9920         otsu_vv    -10.922461
tana_500_9920  change_otsu_vv      0.614300
tana_500_9920 change_fixed_vv     -3.000000
tana_500_9920         otsu_vh    -17.688643
tana_500_9920  change_otsu_vh      0.984905
tana_500_9920 change_fixed_vh     -3.000000
tana_500_9920       unet_post           NaN
tana_500_9920  unet_post_hand           NaN
tana_500_9920        unet_pre           NaN
tana_500_9980         otsu_vv    -12.591230
tana_500_9980  change_otsu_vv     -0.258741
tana_500_9980 change_fixed_vv     -3.000000
tana_500_9980         otsu_vh    -21.009802
tana_500_9980  change_otsu_vh      4.586745
tana_500_9980 change_fixed_vh     -3.000000
tana_500_9980       unet_post           NaN
tana_500_9980  unet_post_hand           NaN
tana_500_9980        unet_pre           NaN
tana_520_9580         otsu_vv    -12.089715
tana_520_9580  change_otsu_vv      0.528864
tana_520_9580 change_fixed_vv     -3.000000
tana_520_9580         otsu_vh    -17.457925
tana_520_9580  change_otsu_vh      0.059691
tana_520_9580 change_fixed_vh     -3.000000
tana_520_9580       unet_post           NaN
tana_520_9580  unet_post_hand           NaN
tana_520_9580        unet_pre           NaN
tana_520_9600         otsu_vv    -11.567975
tana_520_9600  change_otsu_vv      1.426261
tana_520_9600 change_fixed_vv     -3.000000
tana_520_9600         otsu_vh    -17.020439
tana_520_9600  change_otsu_vh      1.397379
tana_520_9600 change_fixed_vh     -3.000000
tana_520_9600       unet_post           NaN
tana_520_9600  unet_post_hand           NaN
tana_520_9600        unet_pre           NaN
tana_520_9640         otsu_vv    -15.196248
tana_520_9640  change_otsu_vv      1.899945
tana_520_9640 change_fixed_vv     -3.000000
tana_520_9640         otsu_vh    -23.735305
tana_520_9640  change_otsu_vh      2.795126
tana_520_9640 change_fixed_vh     -3.000000
tana_520_9640       unet_post           NaN
tana_520_9640  unet_post_hand           NaN
tana_520_9640        unet_pre           NaN
tana_520_9660         otsu_vv    -15.806368
tana_520_9660  change_otsu_vv      0.878440
tana_520_9660 change_fixed_vv     -3.000000
tana_520_9660         otsu_vh    -23.225965
tana_520_9660  change_otsu_vh      1.399499
tana_520_9660 change_fixed_vh     -3.000000
tana_520_9660       unet_post           NaN
tana_520_9660  unet_post_hand           NaN
tana_520_9660        unet_pre           NaN
tana_520_9960         otsu_vv    -11.988760
tana_520_9960  change_otsu_vv      2.421647
tana_520_9960 change_fixed_vv     -3.000000
tana_520_9960         otsu_vh    -19.679316
tana_520_9960  change_otsu_vh      2.266341
tana_520_9960 change_fixed_vh     -3.000000
tana_520_9960       unet_post           NaN
tana_520_9960  unet_post_hand           NaN
tana_520_9960        unet_pre           NaN
tana_520_9980         otsu_vv    -14.200366
tana_520_9980  change_otsu_vv     -2.770724
tana_520_9980 change_fixed_vv     -3.000000
tana_520_9980         otsu_vh    -22.208689
tana_520_9980  change_otsu_vh     -1.673315
tana_520_9980 change_fixed_vh     -3.000000
tana_520_9980       unet_post           NaN
tana_520_9980  unet_post_hand           NaN
tana_520_9980        unet_pre           NaN
tana_540_9600         otsu_vv    -13.253456
tana_540_9600  change_otsu_vv      0.495282
tana_540_9600 change_fixed_vv     -3.000000
tana_540_9600         otsu_vh    -19.188415
tana_540_9600  change_otsu_vh     -0.011587
tana_540_9600 change_fixed_vh     -3.000000
tana_540_9600       unet_post           NaN
tana_540_9600  unet_post_hand           NaN
tana_540_9600        unet_pre           NaN
tana_540_9620         otsu_vv    -11.905109
tana_540_9620  change_otsu_vv      0.381419
tana_540_9620 change_fixed_vv     -3.000000
tana_540_9620         otsu_vh    -18.521752
tana_540_9620  change_otsu_vh     -0.024847
tana_540_9620 change_fixed_vh     -3.000000
tana_540_9620       unet_post           NaN
tana_540_9620  unet_post_hand           NaN
tana_540_9620        unet_pre           NaN
tana_540_9640         otsu_vv    -15.022713
tana_540_9640  change_otsu_vv     -1.841577
tana_540_9640 change_fixed_vv     -3.000000
tana_540_9640         otsu_vh    -23.612171
tana_540_9640  change_otsu_vh     -1.950878
tana_540_9640 change_fixed_vh     -3.000000
tana_540_9640       unet_post           NaN
tana_540_9640  unet_post_hand           NaN
tana_540_9640        unet_pre           NaN
tana_540_9660         otsu_vv    -14.092392
tana_540_9660  change_otsu_vv     -1.783693
tana_540_9660 change_fixed_vv     -3.000000
tana_540_9660         otsu_vh    -23.975556
tana_540_9660  change_otsu_vh     -5.690621
tana_540_9660 change_fixed_vh     -3.000000
tana_540_9660       unet_post           NaN
tana_540_9660  unet_post_hand           NaN
tana_540_9660        unet_pre           NaN
tana_540_9960         otsu_vv    -14.229463
tana_540_9960  change_otsu_vv     -2.684597
tana_540_9960 change_fixed_vv     -3.000000
tana_540_9960         otsu_vh    -21.338898
tana_540_9960  change_otsu_vh     -2.081478
tana_540_9960 change_fixed_vh     -3.000000
tana_540_9960       unet_post           NaN
tana_540_9960  unet_post_hand           NaN
tana_540_9960        unet_pre           NaN
tana_540_9980         otsu_vv    -11.888773
tana_540_9980  change_otsu_vv      1.591867
tana_540_9980 change_fixed_vv     -3.000000
tana_540_9980         otsu_vh    -19.704213
tana_540_9980  change_otsu_vh      2.607611
tana_540_9980 change_fixed_vh     -3.000000
tana_540_9980       unet_post           NaN
tana_540_9980  unet_post_hand           NaN
tana_540_9980        unet_pre           NaN
tana_560_9600         otsu_vv    -11.102532
tana_560_9600  change_otsu_vv     -0.545956
tana_560_9600 change_fixed_vv     -3.000000
tana_560_9600         otsu_vh    -17.136701
tana_560_9600  change_otsu_vh     -0.556414
tana_560_9600 change_fixed_vh     -3.000000
tana_560_9600       unet_post           NaN
tana_560_9600  unet_post_hand           NaN
tana_560_9600        unet_pre           NaN
tana_560_9620         otsu_vv    -10.189592
tana_560_9620  change_otsu_vv      0.186308
tana_560_9620 change_fixed_vv     -3.000000
tana_560_9620         otsu_vh    -16.260532
tana_560_9620  change_otsu_vh     -0.372491
tana_560_9620 change_fixed_vh     -3.000000
tana_560_9620       unet_post           NaN
tana_560_9620  unet_post_hand           NaN
tana_560_9620        unet_pre           NaN
tana_560_9640         otsu_vv    -14.048405
tana_560_9640  change_otsu_vv     -0.994029
tana_560_9640 change_fixed_vv     -3.000000
tana_560_9640         otsu_vh    -23.332460
tana_560_9640  change_otsu_vh     -3.257466
tana_560_9640 change_fixed_vh     -3.000000
tana_560_9640       unet_post           NaN
tana_560_9640  unet_post_hand           NaN
tana_560_9640        unet_pre           NaN
tana_560_9660         otsu_vv    -12.196858
tana_560_9660  change_otsu_vv     -0.568832
tana_560_9660 change_fixed_vv     -3.000000
tana_560_9660         otsu_vh    -20.506380
tana_560_9660  change_otsu_vh     -4.380399
tana_560_9660 change_fixed_vh     -3.000000
tana_560_9660       unet_post           NaN
tana_560_9660  unet_post_hand           NaN
tana_560_9660        unet_pre           NaN
tana_560_9820         otsu_vv    -11.717212
tana_560_9820  change_otsu_vv      0.632032
tana_560_9820 change_fixed_vv     -3.000000
tana_560_9820         otsu_vh    -19.175067
tana_560_9820  change_otsu_vh      0.220818
tana_560_9820 change_fixed_vh     -3.000000
tana_560_9820       unet_post           NaN
tana_560_9820  unet_post_hand           NaN
tana_560_9820        unet_pre           NaN
tana_560_9900         otsu_vv    -11.234864
tana_560_9900  change_otsu_vv      1.646623
tana_560_9900 change_fixed_vv     -3.000000
tana_560_9900         otsu_vh    -17.532136
tana_560_9900  change_otsu_vh      1.700885
tana_560_9900 change_fixed_vh     -3.000000
tana_560_9900       unet_post           NaN
tana_560_9900  unet_post_hand           NaN
tana_560_9900        unet_pre           NaN
tana_560_9920         otsu_vv    -14.067326
tana_560_9920  change_otsu_vv     -0.069998
tana_560_9920 change_fixed_vv     -3.000000
tana_560_9920         otsu_vh    -20.598653
tana_560_9920  change_otsu_vh      0.073924
tana_560_9920 change_fixed_vh     -3.000000
tana_560_9920       unet_post           NaN
tana_560_9920  unet_post_hand           NaN
tana_560_9920        unet_pre           NaN
tana_560_9940         otsu_vv    -13.724632
tana_560_9940  change_otsu_vv     -1.453441
tana_560_9940 change_fixed_vv     -3.000000
tana_560_9940         otsu_vh    -20.593113
tana_560_9940  change_otsu_vh     -1.187977
tana_560_9940 change_fixed_vh     -3.000000
tana_560_9940       unet_post           NaN
tana_560_9940  unet_post_hand           NaN
tana_560_9940        unet_pre           NaN
tana_560_9960         otsu_vv    -13.637757
tana_560_9960  change_otsu_vv     -2.062111
tana_560_9960 change_fixed_vv     -3.000000
tana_560_9960         otsu_vh    -20.313232
tana_560_9960  change_otsu_vh     -1.190712
tana_560_9960 change_fixed_vh     -3.000000
tana_560_9960       unet_post           NaN
tana_560_9960  unet_post_hand           NaN
tana_560_9960        unet_pre           NaN
tana_580_9580         otsu_vv    -13.298631
tana_580_9580  change_otsu_vv      2.045550
tana_580_9580 change_fixed_vv     -3.000000
tana_580_9580         otsu_vh    -23.734375
tana_580_9580  change_otsu_vh      0.988266
tana_580_9580 change_fixed_vh     -3.000000
tana_580_9580       unet_post           NaN
tana_580_9580  unet_post_hand           NaN
tana_580_9580        unet_pre           NaN
tana_580_9600         otsu_vv    -12.171773
tana_580_9600  change_otsu_vv      1.043054
tana_580_9600 change_fixed_vv     -3.000000
tana_580_9600         otsu_vh    -23.481412
tana_580_9600  change_otsu_vh      0.009074
tana_580_9600 change_fixed_vh     -3.000000
tana_580_9600       unet_post           NaN
tana_580_9600  unet_post_hand           NaN
tana_580_9600        unet_pre           NaN
tana_580_9620         otsu_vv    -10.520966
tana_580_9620  change_otsu_vv      0.190242
tana_580_9620 change_fixed_vv     -3.000000
tana_580_9620         otsu_vh    -18.474562
tana_580_9620  change_otsu_vh     -1.019012
tana_580_9620 change_fixed_vh     -3.000000
tana_580_9620       unet_post           NaN
tana_580_9620  unet_post_hand           NaN
tana_580_9620        unet_pre           NaN
tana_580_9640         otsu_vv    -14.248583
tana_580_9640  change_otsu_vv     -0.790327
tana_580_9640 change_fixed_vv     -3.000000
tana_580_9640         otsu_vh    -22.986107
tana_580_9640  change_otsu_vh     -3.832544
tana_580_9640 change_fixed_vh     -3.000000
tana_580_9640       unet_post           NaN
tana_580_9640  unet_post_hand           NaN
tana_580_9640        unet_pre           NaN
tana_580_9860         otsu_vv    -12.750776
tana_580_9860  change_otsu_vv     -1.025381
tana_580_9860 change_fixed_vv     -3.000000
tana_580_9860         otsu_vh    -19.398694
tana_580_9860  change_otsu_vh      2.014060
tana_580_9860 change_fixed_vh     -3.000000
tana_580_9860       unet_post           NaN
tana_580_9860  unet_post_hand           NaN
tana_580_9860        unet_pre           NaN
tana_580_9880         otsu_vv    -13.123629
tana_580_9880  change_otsu_vv      0.757837
tana_580_9880 change_fixed_vv     -3.000000
tana_580_9880         otsu_vh    -19.740758
tana_580_9880  change_otsu_vh      1.289157
tana_580_9880 change_fixed_vh     -3.000000
tana_580_9880       unet_post           NaN
tana_580_9880  unet_post_hand           NaN
tana_580_9880        unet_pre           NaN
tana_580_9900         otsu_vv    -13.936701
tana_580_9900  change_otsu_vv      0.540322
tana_580_9900 change_fixed_vv     -3.000000
tana_580_9900         otsu_vh    -20.385139
tana_580_9900  change_otsu_vh      1.353266
tana_580_9900 change_fixed_vh     -3.000000
tana_580_9900       unet_post           NaN
tana_580_9900  unet_post_hand           NaN
tana_580_9900        unet_pre           NaN
tana_580_9920         otsu_vv    -13.611075
tana_580_9920  change_otsu_vv     -0.046191
tana_580_9920 change_fixed_vv     -3.000000
tana_580_9920         otsu_vh    -20.519204
tana_580_9920  change_otsu_vh      0.146076
tana_580_9920 change_fixed_vh     -3.000000
tana_580_9920       unet_post           NaN
tana_580_9920  unet_post_hand           NaN
tana_580_9920        unet_pre           NaN
tana_600_9600         otsu_vv    -12.629671
tana_600_9600  change_otsu_vv      1.965149
tana_600_9600 change_fixed_vv     -3.000000
tana_600_9600         otsu_vh    -24.309792
tana_600_9600  change_otsu_vh      1.130818
tana_600_9600 change_fixed_vh     -3.000000
tana_600_9600       unet_post           NaN
tana_600_9600  unet_post_hand           NaN
tana_600_9600        unet_pre           NaN
tana_600_9620         otsu_vv    -13.804087
tana_600_9620  change_otsu_vv      1.243825
tana_600_9620 change_fixed_vv     -3.000000
tana_600_9620         otsu_vh    -25.430720
tana_600_9620  change_otsu_vh      1.973239
tana_600_9620 change_fixed_vh     -3.000000
tana_600_9620       unet_post           NaN
tana_600_9620  unet_post_hand           NaN
tana_600_9620        unet_pre           NaN
tana_600_9640         otsu_vv    -13.626831
tana_600_9640  change_otsu_vv     -1.732806
tana_600_9640 change_fixed_vv     -3.000000
tana_600_9640         otsu_vh    -22.900727
tana_600_9640  change_otsu_vh     -4.877955
tana_600_9640 change_fixed_vh     -3.000000
tana_600_9640       unet_post           NaN
tana_600_9640  unet_post_hand           NaN
tana_600_9640        unet_pre           NaN
tana_600_9800         otsu_vv    -12.332899
tana_600_9800  change_otsu_vv     -0.066689
tana_600_9800 change_fixed_vv     -3.000000
tana_600_9800         otsu_vh    -18.276932
tana_600_9800  change_otsu_vh     -0.475342
tana_600_9800 change_fixed_vh     -3.000000
tana_600_9800       unet_post           NaN
tana_600_9800  unet_post_hand           NaN
tana_600_9800        unet_pre           NaN
tana_600_9820         otsu_vv    -13.916882
tana_600_9820  change_otsu_vv     -0.191152
tana_600_9820 change_fixed_vv     -3.000000
tana_600_9820         otsu_vh    -21.289177
tana_600_9820  change_otsu_vh     -0.450263
tana_600_9820 change_fixed_vh     -3.000000
tana_600_9820       unet_post           NaN
tana_600_9820  unet_post_hand           NaN
tana_600_9820        unet_pre           NaN
tana_600_9840         otsu_vv    -13.941710
tana_600_9840  change_otsu_vv      0.669320
tana_600_9840 change_fixed_vv     -3.000000
tana_600_9840         otsu_vh    -21.472875
tana_600_9840  change_otsu_vh      1.407983
tana_600_9840 change_fixed_vh     -3.000000
tana_600_9840       unet_post           NaN
tana_600_9840  unet_post_hand           NaN
tana_600_9840        unet_pre           NaN
tana_600_9860         otsu_vv    -13.880010
tana_600_9860  change_otsu_vv      0.777339
tana_600_9860 change_fixed_vv     -3.000000
tana_600_9860         otsu_vh    -20.381994
tana_600_9860  change_otsu_vh      1.078568
tana_600_9860 change_fixed_vh     -3.000000
tana_600_9860       unet_post           NaN
tana_600_9860  unet_post_hand           NaN
tana_600_9860        unet_pre           NaN
tana_600_9880         otsu_vv    -13.031192
tana_600_9880  change_otsu_vv     -0.247104
tana_600_9880 change_fixed_vv     -3.000000
tana_600_9880         otsu_vh    -19.765288
tana_600_9880  change_otsu_vh      0.215660
tana_600_9880 change_fixed_vh     -3.000000
tana_600_9880       unet_post           NaN
tana_600_9880  unet_post_hand           NaN
tana_600_9880        unet_pre           NaN
tana_620_9620         otsu_vv    -13.356263
tana_620_9620  change_otsu_vv      0.805755
tana_620_9620 change_fixed_vv     -3.000000

## 6. Agreement with UNOSAT

By AOI, by group, by land cover, with and without the HAND mask, with 1 km block bootstrap intervals.

In [7]:
import evaluate

evaluate.main()

/Users/craigouma/Documents/kenya-floods-sar-2024/.venv/lib/python3.12/site-packages/numpy/lib/nanfunctions.py:1384: RuntimeWarning: All-NaN slice encountered
  return _nanquantile_unchecked(

   group          method  hand_mask   iou  iou_lo  iou_hi    f1  precision  recall
riverine       unet_post      False 0.347   0.331   0.364 0.515      0.530   0.500
riverine        unet_pre      False 0.277   0.262   0.293 0.434      0.392   0.486
riverine  unet_post_hand      False 0.212   0.200   0.225 0.349      0.286   0.448
riverine change_fixed_vv      False 0.160   0.150   0.172 0.276      0.275   0.277
riverine change_fixed_vh      False 0.155   0.144   0.168 0.269      0.212   0.366
riverine         otsu_vh      False 0.116   0.109   0.125 0.209      0.151   0.335
riverine         otsu_vv      False 0.082   0.077   0.088 0.152      0.097   0.351
riverine  change_otsu_vh      False 0.064   0.060   0.069 0.121      0.070   0.430
riverine  change_otsu_vv      False 0.064   0.061   0.069 0.121      0.071   0.414
riverine       unet_post       True 0.347   0.331   0.365 0.515      0.531   0.500
riverine        unet_pre       True 0.279   0.264   0.295 0.436      0.395   0.486
riverine  unet_post_hand       True 0.214   0.202   0.228 0.352      0.290   0.448
riverine change_fixed_vv       True 0.162   0.152   0.174 0.279      0.281   0.277
riverine change_fixed_vh       True 0.158   0.147   0.171 0.273      0.218   0.366
riverine         otsu_vh       True 0.122   0.114   0.130 0.217      0.160   0.335
riverine         otsu_vv       True 0.086   0.080   0.092 0.158      0.102   0.351
riverine  change_otsu_vv       True 0.067   0.063   0.071 0.125      0.074   0.414
riverine  change_otsu_vh       True 0.066   0.062   0.071 0.125      0.073   0.430
   urban        unet_pre      False 0.228   0.175   0.282 0.371      0.650   0.259
   urban       unet_post      False 0.221   0.171   0.273 0.362      0.617   0.257
   urban  unet_post_hand      False 0.217   0.167   0.269 0.357      0.623   0.250
   urban         otsu_vh      False 0.192   0.161   0.225 0.322      0.405   0.268
   urban  change_otsu_vv      False 0.175   0.145   0.206 0.298      0.306   0.292
   urban change_fixed_vh      False 0.165   0.130   0.202 0.283      0.567   0.188
   urban  change_otsu_vh      False 0.164   0.140   0.189 0.281      0.227   0.369
   urban         otsu_vv      False 0.158   0.137   0.180 0.273      0.164   0.824
   urban change_fixed_vv      False 0.151   0.115   0.189 0.262      0.622   0.166
   urban        unet_pre       True 0.228   0.175   0.283 0.371      0.653   0.259
   urban       unet_post       True 0.222   0.172   0.274 0.363      0.623   0.257
   urban  unet_post_hand       True 0.218   0.167   0.270 0.358      0.627   0.250
   urban         otsu_vh       True 0.195   0.164   0.228 0.327      0.420   0.267
   urban  change_otsu_vv       True 0.180   0.150   0.212 0.305      0.320   0.291
   urban  change_otsu_vh       True 0.170   0.146   0.196 0.291      0.240   0.369
   urban change_fixed_vh       True 0.166   0.131   0.203 0.284      0.580   0.188
   urban         otsu_vv       True 0.166   0.143   0.188 0.284      0.172   0.820
   urban change_fixed_vv       True 0.151   0.116   0.190 0.263      0.633   0.166

## 7. Day-gap sensitivity and building exposure

In [8]:
import sensitivity, exposure

sensitivity.main()
exposure.main()

using day_gap_sensitivity.csv; pass force=True to recompute

       aoi    group  buildings_in_domain  unosat_structures_in_domain  unosat_structures_layer          method  exposed  ratio_to_unosat
garissa_s2 riverine                84681                         3440                     3440   unosat_extent     2481            0.721
garissa_s2 riverine                84681                         3440                     3440 change_fixed_vh     1919            0.558
garissa_s2 riverine                84681                         3440                     3440 change_fixed_vv     1379            0.401
garissa_s2 riverine                84681                         3440                     3440  change_otsu_vh     5455            1.586
garissa_s2 riverine                84681                         3440                     3440  change_otsu_vv     3734            1.085
garissa_s2 riverine                84681                         3440                     3440         otsu_vh      797            0.232
garissa_s2 riverine                84681                         3440                     3440         otsu_vv      594            0.173
garissa_s2 riverine                84681                         3440                     3440       unet_post      116            0.034
garissa_s2 riverine                84681                         3440                     3440  unet_post_hand      199            0.058
garissa_s2 riverine                84681                         3440                     3440        unet_pre      145            0.042
garissa_pl riverine                81178                         3377                     3377   unosat_extent     4241            1.256
garissa_pl riverine                81178                         3377                     3377 change_fixed_vh     3417            1.012
garissa_pl riverine                81178                         3377                     3377 change_fixed_vv     2557            0.757
garissa_pl riverine                81178                         3377                     3377  change_otsu_vh      207            0.061
garissa_pl riverine                81178                         3377                     3377  change_otsu_vv     1546            0.458
garissa_pl riverine                81178                         3377                     3377         otsu_vh      327            0.097
garissa_pl riverine                81178                         3377                     3377         otsu_vv      657            0.195
garissa_pl riverine                81178                         3377                     3377       unet_post      488            0.145
garissa_pl riverine                81178                         3377                     3377  unet_post_hand      259            0.077
garissa_pl riverine                81178                         3377                     3377        unet_pre      852            0.252
nairobi_pl    urban               505822                        12985                    13111   unosat_extent     8736            0.673
nairobi_pl    urban               505822                        12985                    13111 change_fixed_vh    10166            0.783
nairobi_pl    urban               505822                        12985                    13111 change_fixed_vv     7246            0.558
nairobi_pl    urban               505822                        12985                    13111  change_otsu_vh   124981            9.625
nairobi_pl    urban               505822                        12985                    13111  change_otsu_vv    69866            5.381
nairobi_pl    urban               505822                        12985                    13111         otsu_vh     1484            0.114
nairobi_pl    urban               505822                        12985                    13111         otsu_vv    61591            4.743
nairobi_pl    urban               505822                        12985                    13111       unet_post      757            0.058
nairobi_pl    urban               505822                        12985                    13111  unet_post_hand      691            0.053
nairobi_pl    urban               505822                        12985                    13111        unet_pre      886            0.068

## 8. Lower Tana flood time series

In [9]:
import tana_timeseries

TANA_METHOD = (ROOT / 'outputs' / 'tana_method.txt').read_text().strip()
tana_timeseries.build(TANA_METHOD)

I1010 14:46:41.694796 10583428 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
I1010 14:46:41.723147 10613248 ev_poll_posix.cc:587] FD from fork parent still in poll list: fd(103, generation: 1)

I1010 14:46:42.052406 10583428 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers

I1010 14:46:42.076823 10583428 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
I1010 14:46:42.082582 10613263 ev_poll_posix.cc:587] FD from fork parent still in poll list: fd(103, generation: 1)
I1010 14:46:42.107125 10613278 ev_poll_posix.cc:587] FD from fork parent still in poll list: fd(103, generation: 1)

garissa_s2 7 passes
tana_500_9660 7 passes

tana_500_9920 7 passes
tana_500_9900 7 passes

tana_500_9980 7 passes

tana_520_9660 14 passes

tana_520_9960 7 passes

tana_520_9980 7 passes

tana_540_9960 7 passes

tana_540_9980 7 passes

tana_560_9820 7 passes

tana_560_9900 7 passes

tana_560_9920 7 passes

tana_560_9940 7 passes

tana_560_9960 7 passes

tana_580_9860 7 passes

tana_580_9880 7 passes

tana_580_9900 7 passes

tana_580_9920 7 passes

tana_600_9800 7 passes

tana_600_9820 7 passes

tana_600_9840 7 passes

tana_600_9860 7 passes

tana_600_9880 7 passes

tana_620_9700 7 passes

tana_620_9680 7 passes

tana_620_9740 7 passes

tana_620_9760 7 passes

tana_620_9780 7 passes

tana_620_9800 7 passes

tana_620_9820 7 passes

tana_640_9700 7 passes

tana_640_9720 7 passes

tana_660_9720 7 passes

tana_660_9820 7 passes

tana_680_9720 7 passes

tana_680_9820 7 passes

tana_680_9840 7 passes

    orbit        date      county  observed_km2  flooded_km2
0      57  2024-04-07     Garissa        0.0000       0.0000
1      57  2024-04-07  Tana River      204.5960      19.3310
2      57  2024-04-19     Garissa        0.0000       0.0000
3      57  2024-04-19  Tana River      204.5960      29.5803
4      57  2024-05-01     Garissa        0.0000       0.0000
5      57  2024-05-01  Tana River      204.5960      62.6490
6      57  2024-05-25     Garissa        0.0000       0.0000
7      57  2024-05-25  Tana River      204.5960      95.0952
8      57  2024-06-06     Garissa        0.0000       0.0000
9      57  2024-06-06  Tana River      204.5960     111.7737
10     57  2024-06-18     Garissa        0.0000       0.0000
11     57  2024-06-18  Tana River      204.5960     122.4327
12     57  2024-06-30     Garissa        0.0000       0.0000
13     57  2024-06-30  Tana River      204.5960      96.2308
14    159  2024-04-02     Garissa     1682.4234      10.2069
15    159  2024-04-02  Tana River     5754.6738     235.7292
16    159  2024-04-14     Garissa     1682.4242       7.6021
17    159  2024-04-14  Tana River     5754.6732     270.4522
18    159  2024-04-26     Garissa     1682.4232       8.2498
19    159  2024-04-26  Tana River     5754.6736     330.0274
20    159  2024-05-08     Garissa     1682.4639      13.7944
21    159  2024-05-08  Tana River     5754.8030     482.0470
22    159  2024-05-20     Garissa     1682.4243      10.7051
23    159  2024-05-20  Tana River     5754.6734     535.4178
24    159  2024-06-13     Garissa     1682.4242      10.7364
25    159  2024-06-13  Tana River     5754.6735     396.0922
26    159  2024-06-25     Garissa     1682.4232       9.9267
27    159  2024-06-25  Tana River     5754.6736     343.2061

## 9. Figures

In [10]:
import figures

figures.main()